import { StyleSheet, Text, View } from 'react-native';
import { Bot, Check, Clock3, MessageCircle, Send, X } from 'lucide-react-native';
import { AppShell } from '@/components/AppShell';
import { Eyebrow, PageHeader, SectionCard, StatusBadge } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { colors, radii } from '@/theme';

export default function ActivityPage(){const {activity,campaigns}=useApp();const sent=campaigns.reduce((n,c)=>n+c.sent,0);const failed=campaigns.reduce((n,c)=>n+c.failed,0);return <AppShell><PageHeader eyebrow="System timeline" title="Every important action, visible." description="A concise record of campaigns, outgoing messages, incoming chats and AI replies."/>
  <View style={styles.metrics}><Summary label="Sent" value={sent} tone="acid"/><Summary label="Failed" value={failed} tone="danger"/><Summary label="Events" value={activity.length} tone="light"/></View>
  <SectionCard><Eyebrow>Recent activity</Eyebrow>{activity.length===0?<View style={styles.empty}><Clock3 size={34} color={colors.line}/><Text style={styles.emptyTitle}>Nothing to report yet</Text><Text style={styles.emptyText}>Connection, campaign and AI events will appear here.</Text></View>:activity.map((event,index)=>{const Icon=event.type==='ai'?Bot:event.type==='inbound'?MessageCircle:event.type==='message'?Send:Clock3;const bad=event.status==='failed';return <View style={styles.event} key={event.id}><View style={styles.timeline}><View style={[styles.eventIcon,bad&&styles.eventIconBad]}><Icon size={17} color={colors.ink}/></View>{index<activity.length-1&&<View style={styles.line}/>}</View><View style={styles.eventBody}><Text style={styles.eventTitle}>{event.title}</Text><Text style={styles.eventDetail}>{event.detail}</Text></View><Text style={styles.eventTime}>{new Date(event.created_at).toLocaleString()}</Text><StatusBadge label={event.status} tone={bad?'danger':event.status==='sent'?'success':'neutral'}/></View>})}</SectionCard>
  </AppShell>}
function Summary({label,value,tone}:{label:string;value:number;tone:'acid'|'danger'|'light'}){return <View style={[styles.summary,tone==='acid'&&styles.summaryAcid,tone==='danger'&&styles.summaryDanger]}><Text style={styles.summaryLabel}>{label}</Text><Text style={styles.summaryValue}>{String(value).padStart(2,'0')}</Text><View style={styles.summaryIcon}>{tone==='danger'?<X size={16} color={colors.ink}/>:<Check size={16} color={colors.ink}/>}</View></View>}
const styles=StyleSheet.create({metrics:{flexDirection:'row',flexWrap:'wrap',gap:12,marginBottom:20},summary:{minWidth:150,flex:1,maxWidth:260,minHeight:120,borderRadius:radii.large,backgroundColor:colors.card,padding:20},summaryAcid:{backgroundColor:colors.acid},summaryDanger:{backgroundColor:'#EDCBC7'},summaryLabel:{fontFamily:'Manrope_600SemiBold',fontSize:10,color:colors.muted,textTransform:'uppercase'},summaryValue:{fontFamily:'Manrope_500Medium',fontSize:34,color:colors.ink,marginTop:6},summaryIcon:{position:'absolute',right:16,bottom:16,width:32,height:32,borderRadius:16,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},empty:{minHeight:300,alignItems:'center',justifyContent:'center'},emptyTitle:{fontFamily:'Manrope_700Bold',fontSize:18,color:colors.ink,marginTop:12},emptyText:{fontFamily:'Manrope_400Regular',fontSize:12,color:colors.muted,marginTop:4},event:{minHeight:74,flexDirection:'row',alignItems:'center',gap:14},timeline:{alignSelf:'stretch',alignItems:'center'},eventIcon:{width:42,height:42,borderRadius:21,backgroundColor:colors.acid,alignItems:'center',justifyContent:'center',zIndex:2},eventIconBad:{backgroundColor:'#EDCBC7'},line:{position:'absolute',top:42,bottom:-32,width:1,backgroundColor:colors.line},eventBody:{flex:1},eventTitle:{fontFamily:'Manrope_700Bold',fontSize:13,color:colors.ink},eventDetail:{fontFamily:'Manrope_400Regular',fontSize:10,color:colors.muted,marginTop:3},eventTime:{fontFamily:'Manrope_400Regular',fontSize:9,color:colors.muted},});
