import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Switch,   useWindowDimensions, View } from 'react-native';
import { TextInput, Text } from '@/i18n';
import { Bot, KeyRound, MessageCircle, Save, ShieldCheck, Sparkles } from 'lucide-react-native';
import { AppShell } from '@/components/AppShell';
import { ActionButton, Eyebrow, PageHeader, SectionCard, StatusBadge } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { colors, radii } from '@/theme';

const models=['gpt-5-mini','gpt-5','gpt-4.1-mini'];
export default function AiPage(){
  const {width}=useWindowDimensions();const narrow=width<900;const {api,ai,setAi,whatsapp}=useApp();
  const [enabled,setEnabled]=useState(ai.enabled);const [prompt,setPrompt]=useState(ai.prompt);const [model,setModel]=useState(ai.model);const [apiKey,setApiKey]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState<string|null>(null);
  useEffect(()=>{setEnabled(ai.enabled);setPrompt(ai.prompt);setModel(ai.model)},[ai]);
  const save=async()=>{setBusy(true);setNotice(null);try{const saved=await api.saveAiSettings({enabled,prompt,model,...(apiKey.trim()?{apiKey}: {})});setAi(saved);setApiKey('');setNotice('AI settings saved securely.');}catch(e){setNotice(e instanceof Error?e.message:String(e));}finally{setBusy(false)}};
  return <AppShell><PageHeader eyebrow="AI customer care" title="Give every reply a clear personality." description="Define the assistant once. It will answer direct customer messages only, with recent conversation context and your business instructions." action={<StatusBadge label={enabled?'AI replies on':'AI replies off'} tone={enabled?'acid':'neutral'}/>}/>
    <View style={[styles.grid,narrow&&styles.stack]}>
      <View style={styles.main}>
        <SectionCard><View style={styles.cardHeader}><View><Eyebrow>Assistant identity</Eyebrow><Text style={styles.cardTitle}>System prompt</Text></View><View style={styles.spark}><Sparkles size={22} color={colors.ink}/></View></View><TextInput value={prompt} onChangeText={setPrompt} multiline maxLength={20000} textAlignVertical="top" placeholder="Describe your business, products, tone, policies, opening hours and how the assistant should behave..." placeholderTextColor="#9B9F99" style={styles.prompt}/><View style={styles.promptFooter}><Text style={styles.helper}>Be explicit about prices, policies and when to ask for a human.</Text><Text style={styles.count}>{prompt.length} / 20,000</Text></View></SectionCard>
        <SectionCard style={{marginTop:18}}><Eyebrow>Model</Eyebrow><View style={styles.models}>{models.map(item=><Pressable key={item} onPress={()=>setModel(item)} style={[styles.model,model===item&&styles.modelActive]}><Bot size={17} color={colors.ink}/><Text style={styles.modelText}>{item}</Text></Pressable>)}</View></SectionCard>
      </View>
      <View style={styles.side}>
        <SectionCard><Eyebrow>OpenAI access</Eyebrow><Text style={styles.cardTitle}>API key</Text><View style={styles.keyBox}><KeyRound size={18} color={colors.muted}/><TextInput value={apiKey} onChangeText={setApiKey} secureTextEntry autoCapitalize="none" autoCorrect={false} placeholder={ai.configured?'Saved · enter only to replace':'sk-...'} placeholderTextColor="#9B9F99" style={styles.keyInput}/></View><View style={styles.secureLine}><ShieldCheck size={15} color={colors.success}/><Text style={styles.secureText}>Encrypted on the backend and never returned to the app.</Text></View></SectionCard>
        <SectionCard style={styles.toggleCard}><View style={styles.toggleIcon}><MessageCircle size={22} color={colors.ink}/></View><View style={{flex:1}}><Text style={styles.toggleTitle}>Automatic replies</Text><Text style={styles.toggleText}>Direct chats only. Groups and status messages are ignored.</Text></View><Switch value={enabled} onValueChange={setEnabled} trackColor={{false:'#C7C9C3',true:colors.acidSoft}} thumbColor={enabled?colors.ink:colors.white}/></SectionCard>
        <View style={styles.readiness}><Text style={styles.readinessTitle}>Readiness</Text><Ready label="WhatsApp linked" ready={whatsapp.state==='connected'}/><Ready label="API key configured" ready={ai.configured||Boolean(apiKey.trim())}/><Ready label="Prompt is detailed" ready={prompt.trim().length>=20}/></View>
        <ActionButton label="Save AI settings" variant="acid" onPress={save} loading={busy} disabled={prompt.trim().length<20||(!ai.configured&&!apiKey.trim())} icon={<Save size={18} color={colors.ink}/>}/>{notice&&<Text style={styles.notice}>{notice}</Text>}
      </View>
    </View>
  </AppShell>;
}
function Ready({label,ready}:{label:string;ready:boolean}){return <View style={styles.readyRow}><View style={[styles.readyDot,ready&&styles.readyDotOn]}/><Text style={styles.readyText}>{label}</Text><Text style={styles.readyStatus}>{ready?'Ready':'Needed'}</Text></View>}
const styles=StyleSheet.create({
  grid:{flexDirection:'row',gap:20,alignItems:'flex-start'},stack:{flexDirection:'column'},main:{flex:1.2},side:{flex:.72,gap:18},cardHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},cardTitle:{fontFamily:'Manrope_500Medium',fontSize:24,color:colors.ink},spark:{width:48,height:48,borderRadius:24,backgroundColor:colors.acid,alignItems:'center',justifyContent:'center'},prompt:{minHeight:330,marginTop:18,backgroundColor:colors.canvas,borderRadius:radii.medium,padding:20,fontFamily:'Manrope_400Regular',fontSize:14,lineHeight:23,color:colors.ink,borderWidth:1,borderColor:colors.line},promptFooter:{flexDirection:'row',justifyContent:'space-between',gap:10,marginTop:10},helper:{fontFamily:'Manrope_400Regular',fontSize:10,color:colors.muted,flex:1},count:{fontFamily:'Manrope_600SemiBold',fontSize:10,color:colors.muted},models:{flexDirection:'row',flexWrap:'wrap',gap:9},model:{minHeight:44,paddingHorizontal:14,borderRadius:radii.pill,backgroundColor:colors.canvas,flexDirection:'row',alignItems:'center',gap:8},modelActive:{backgroundColor:colors.acid},modelText:{fontFamily:'Manrope_600SemiBold',fontSize:12,color:colors.ink},
  keyBox:{marginTop:16,minHeight:54,borderRadius:radii.medium,backgroundColor:colors.canvas,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:colors.line},keyInput:{flex:1,fontFamily:'Manrope_500Medium',fontSize:13,color:colors.ink},secureLine:{flexDirection:'row',gap:8,alignItems:'flex-start',marginTop:12},secureText:{flex:1,fontFamily:'Manrope_400Regular',fontSize:10,lineHeight:15,color:colors.muted},toggleCard:{flexDirection:'row',alignItems:'center',gap:12},toggleIcon:{width:48,height:48,borderRadius:24,backgroundColor:colors.acid,alignItems:'center',justifyContent:'center'},toggleTitle:{fontFamily:'Manrope_700Bold',fontSize:14,color:colors.ink},toggleText:{fontFamily:'Manrope_400Regular',fontSize:10,lineHeight:15,color:colors.muted,marginTop:3},readiness:{backgroundColor:colors.ink,borderRadius:radii.large,padding:20},readinessTitle:{fontFamily:'Manrope_700Bold',fontSize:15,color:colors.white,marginBottom:10},readyRow:{flexDirection:'row',alignItems:'center',gap:9,minHeight:35,borderTopWidth:1,borderTopColor:'#3D4441'},readyDot:{width:8,height:8,borderRadius:8,backgroundColor:colors.danger},readyDotOn:{backgroundColor:colors.acid},readyText:{flex:1,fontFamily:'Manrope_400Regular',fontSize:11,color:'#D5D8D4'},readyStatus:{fontFamily:'Manrope_700Bold',fontSize:9,color:'#9FA49F'},notice:{fontFamily:'Manrope_600SemiBold',fontSize:11,color:colors.ink,backgroundColor:colors.acid,padding:10,borderRadius:12,textAlign:'center'},
});
