import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';
import { Check, Clock3, Pause, Play, Send, Users } from 'lucide-react-native';
import { AppShell } from '@/components/AppShell';
import { ActionButton, Eyebrow, PageHeader, SectionCard, StatusBadge } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { colors, radii } from '@/theme';

export default function CampaignPage(){
  const {width}=useWindowDimensions(); const narrow=width<940; const {api,whatsapp,campaigns,refresh}=useApp();
  const [numbers,setNumbers]=useState(''); const [message,setMessage]=useState(''); const [consent,setConsent]=useState(false); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState<string|null>(null);
  const parsed=useMemo(()=>numbers.split(/[\n,;]+/).map(v=>v.trim()).filter(Boolean),[numbers]); const active=campaigns.find(c=>c.status==='running'||c.status==='paused');
  const run=async()=>{setBusy(true);setNotice(null);try{const result=await api.createCampaign(parsed,message);setNotice(result.invalid.length?`Started. ${result.invalid.length} invalid number(s) skipped.`:'Campaign started successfully.');setNumbers('');setMessage('');setConsent(false);await refresh();}catch(e){setNotice(e instanceof Error?e.message:String(e));}finally{setBusy(false)}};
  const action=async(id:string,type:'stop'|'resume')=>{setBusy(true);try{await api.campaignAction(id,type);await refresh();}catch(e){setNotice(e instanceof Error?e.message:String(e));}finally{setBusy(false)}};
  return <AppShell><PageHeader eyebrow="Outbound campaign" title="One message. A deliberate rhythm." description="Add opted-in customers, write one message, and Platinum sends to each number with a fixed ten-minute interval." action={<StatusBadge label={whatsapp.state==='connected'?'WhatsApp ready':'Connect WhatsApp first'} tone={whatsapp.state==='connected'?'success':'warning'}/>}/>
    <View style={[styles.metrics,narrow&&styles.metricsWrap]}><Metric icon={<Users size={19} color={colors.ink}/>} label="Recipients" value={String(parsed.length).padStart(2,'0')}/><Metric icon={<Clock3 size={19} color={colors.ink}/>} label="Interval" value="10 min"/><Metric icon={<Send size={19} color={colors.ink}/>} label="Delivered" value={String(active?.sent||0).padStart(2,'0')}/></View>
    <View style={[styles.builder,narrow&&styles.stack]}>
      <SectionCard style={styles.panel}><View style={styles.panelHeader}><View><Eyebrow>01 · Audience</Eyebrow><Text style={styles.panelTitle}>Customer numbers</Text></View><View style={styles.counter}><Text style={styles.counterText}>{parsed.length}</Text></View></View><View style={[styles.inputFrame,styles.numberInput]}><TextInput testID="campaign-numbers" value={numbers} onChangeText={setNumbers} multiline placeholder={'+962 79 000 0000\n+971 50 000 0000\n+1 202 555 0100'} placeholderTextColor="#A4A7A2" style={styles.input} textAlignVertical="top"/></View><Text style={styles.hint}>International format · one number per line · duplicates are removed</Text></SectionCard>
      <View style={[styles.connector,!narrow&&styles.connectorHorizontal]}><View style={styles.connectorDot}><Clock3 size={18} color={colors.ink}/></View><View style={styles.connectorLine}/><Text style={styles.connectorText}>10 MIN</Text></View>
      <SectionCard style={styles.panel}><View style={styles.panelHeader}><View><Eyebrow>02 · Message</Eyebrow><Text style={styles.panelTitle}>What should we send?</Text></View><View style={styles.counter}><Text style={styles.counterText}>{message.length}</Text></View></View><View style={[styles.inputFrame,styles.messageInput]}><TextInput testID="campaign-message" value={message} onChangeText={setMessage} multiline maxLength={4096} placeholder="Write the exact WhatsApp message..." placeholderTextColor="#A4A7A2" style={styles.input} textAlignVertical="top"/></View><Pressable onPress={()=>setConsent(!consent)} style={styles.consent}><View style={[styles.checkbox,consent&&styles.checkboxOn]}>{consent&&<Check size={15} color={colors.ink}/>}</View><Text style={styles.consentText}>These recipients gave permission to receive this message.</Text></Pressable></SectionCard>
    </View>
    <View style={styles.runBar}><View><Text style={styles.runTitle}>{active?`${active.sent + active.failed} of ${active.total} processed`:'Ready when you are'}</Text><Text style={styles.runSub}>{active?.next_send_at?`Next action ${new Date(active.next_send_at).toLocaleString()}`:'The first message is sent immediately after Run.'}</Text></View><View style={styles.runActions}>{active?.status==='running'?<ActionButton label="Stop" variant="light" onPress={()=>action(active.id,'stop')} loading={busy} icon={<Pause size={18} color={colors.ink}/>}/>:active?.status==='paused'?<ActionButton label="Resume" variant="acid" onPress={()=>action(active.id,'resume')} loading={busy} icon={<Play size={18} color={colors.ink}/>}/>:<ActionButton label="Run campaign" variant="acid" onPress={run} loading={busy} disabled={!consent||!parsed.length||!message.trim()||whatsapp.state!=='connected'} icon={<Play size={18} color={colors.ink}/>}/>}</View></View>
    {notice&&<Text style={styles.notice}>{notice}</Text>}
    <SectionCard style={{marginTop:20}}><Eyebrow>Campaign history</Eyebrow>{campaigns.length===0?<Text style={styles.empty}>No campaigns yet. Your first run will appear here.</Text>:campaigns.slice(0,6).map(c=><View key={c.id} style={styles.row}><View style={styles.rowMain}><Text numberOfLines={1} style={styles.rowMessage}>{c.message}</Text><Text style={styles.rowMeta}>{new Date(c.created_at).toLocaleString()} · {c.total} recipients</Text></View><Text style={styles.rowCount}>{c.sent}/{c.total}</Text><StatusBadge label={c.status} tone={c.status==='completed'?'success':c.status==='running'?'acid':'warning'}/></View>)}</SectionCard>
  </AppShell>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <View style={styles.metric}><View style={styles.metricIcon}>{icon}</View><View><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View></View>}
const styles=StyleSheet.create({
  metrics:{flexDirection:'row',gap:12,marginBottom:20},metricsWrap:{flexWrap:'wrap'},metric:{minWidth:170,flex:1,backgroundColor:colors.card,borderRadius:radii.pill,padding:12,flexDirection:'row',alignItems:'center',gap:12},metricIcon:{width:42,height:42,borderRadius:21,backgroundColor:colors.acid,alignItems:'center',justifyContent:'center'},metricLabel:{fontFamily:'Manrope_600SemiBold',fontSize:10,color:colors.muted,textTransform:'uppercase'},metricValue:{fontFamily:'Manrope_600SemiBold',fontSize:19,color:colors.ink},
  builder:{flexDirection:'row',alignItems:'stretch'},stack:{flexDirection:'column'},panel:{flex:1,minHeight:390},panelHeader:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',marginBottom:16},panelTitle:{fontFamily:'Manrope_500Medium',fontSize:23,color:colors.ink},counter:{minWidth:44,height:34,borderRadius:radii.pill,backgroundColor:'#DFE0DA',alignItems:'center',justifyContent:'center'},counterText:{fontFamily:'Manrope_700Bold',fontSize:11,color:colors.ink},inputFrame:{overflow:'hidden',backgroundColor:colors.canvas,borderRadius:radii.medium,borderWidth:1,borderColor:colors.line},input:{flex:1,borderWidth:0,padding:18,paddingRight:12,fontFamily:'Manrope_500Medium',fontSize:15,color:colors.ink},numberInput:{minHeight:235},messageInput:{minHeight:210},hint:{fontFamily:'Manrope_400Regular',fontSize:11,color:colors.muted,marginTop:12},
  connector:{height:76,alignItems:'center',justifyContent:'center'},connectorHorizontal:{width:100,height:'auto'},connectorDot:{width:48,height:48,borderRadius:24,backgroundColor:colors.acid,alignItems:'center',justifyContent:'center',zIndex:2},connectorLine:{position:'absolute',height:1,left:0,right:0,backgroundColor:colors.ink},connectorText:{fontFamily:'Manrope_700Bold',fontSize:8,color:colors.muted,marginTop:6},consent:{flexDirection:'row',alignItems:'center',gap:10,marginTop:16},checkbox:{width:22,height:22,borderRadius:7,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},checkboxOn:{backgroundColor:colors.acid,borderColor:colors.acid},consentText:{fontFamily:'Manrope_400Regular',fontSize:12,color:colors.inkSoft,flex:1},
  runBar:{marginTop:20,borderRadius:radii.large,backgroundColor:colors.ink,padding:20,paddingLeft:26,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:20},runTitle:{fontFamily:'Manrope_700Bold',fontSize:16,color:colors.white},runSub:{fontFamily:'Manrope_400Regular',fontSize:11,color:'#B9BDB9',marginTop:4},runActions:{minWidth:160},notice:{fontFamily:'Manrope_600SemiBold',fontSize:12,color:colors.ink,backgroundColor:colors.acid,padding:12,borderRadius:14,marginTop:12},empty:{fontFamily:'Manrope_400Regular',fontSize:13,color:colors.muted,paddingVertical:20},row:{flexDirection:'row',alignItems:'center',gap:16,paddingVertical:14,borderTopWidth:1,borderTopColor:colors.line},rowMain:{flex:1},rowMessage:{fontFamily:'Manrope_600SemiBold',fontSize:13,color:colors.ink},rowMeta:{fontFamily:'Manrope_400Regular',fontSize:10,color:colors.muted,marginTop:4},rowCount:{fontFamily:'Manrope_700Bold',fontSize:13,color:colors.ink},
});
