import { useState } from 'react';
import { Platform, StyleSheet, Text, TextInput, View } from 'react-native';
import { Check, Globe2, Save, Server, Smartphone } from 'lucide-react-native';
import { AppShell } from '@/components/AppShell';
import { ActionButton, Eyebrow, PageHeader, SectionCard, StatusBadge } from '@/components/UI';
import { useApp } from '@/context/AppContext';
import { colors, radii } from '@/theme';

export default function SettingsPage(){const {apiUrl,setApiUrl,online}=useApp();const [value,setValue]=useState(apiUrl);const [notice,setNotice]=useState<string|null>(null);const save=async()=>{if(!/^https?:\/\//i.test(value.trim())){setNotice('Use a complete http:// or https:// address.');return;}await setApiUrl(value);setNotice('Server address saved on this device.');};return <AppShell><PageHeader eyebrow="Application settings" title="One backend. Every screen." description="Choose the Platinum API address used by this web or mobile installation." action={<StatusBadge label={online?'API online':'API offline'} tone={online?'success':'danger'}/>}/>
  <View style={styles.layout}><SectionCard style={styles.main}><View style={styles.head}><View><Eyebrow>Backend endpoint</Eyebrow><Text style={styles.title}>API server address</Text></View><View style={styles.icon}><Server size={24} color={colors.ink}/></View></View><View style={styles.field}><Globe2 size={19} color={colors.muted}/><TextInput value={value} onChangeText={setValue} autoCapitalize="none" autoCorrect={false} keyboardType="url" style={styles.input} placeholder="http://192.168.1.20:8787" placeholderTextColor="#969A95"/></View><Text style={styles.help}>{Platform.OS==='web'?'For this computer, localhost works when the backend runs here.':'For a real phone, use the computer’s local network IP—not localhost.'}</Text><View style={styles.action}><ActionButton label="Save address" variant="dark" onPress={save} icon={<Save size={18} color={colors.white}/>}/></View>{notice&&<Text style={styles.notice}>{notice}</Text>}</SectionCard>
  <SectionCard style={styles.info}><Eyebrow>Platform readiness</Eyebrow><Ready icon={<Globe2 size={18} color={colors.ink}/>} title="Web" text="Static Expo export ready"/><Ready icon={<Smartphone size={18} color={colors.ink}/>} title="Android & iOS" text="Shared React Native interface"/><Ready icon={<Server size={18} color={colors.ink}/>} title="Backend" text="Runs separately, 24/7"/></SectionCard></View>
  </AppShell>}
function Ready({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <View style={styles.ready}><View style={styles.readyIcon}>{icon}</View><View style={{flex:1}}><Text style={styles.readyTitle}>{title}</Text><Text style={styles.readyText}>{text}</Text></View><Check size={18} color={colors.success}/></View>}
const styles=StyleSheet.create({layout:{flexDirection:'row',flexWrap:'wrap',gap:20,alignItems:'flex-start'},main:{flex:1,minWidth:300},info:{width:360,maxWidth:'100%'},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},title:{fontFamily:'Manrope_500Medium',fontSize:25,color:colors.ink},icon:{width:52,height:52,borderRadius:26,backgroundColor:colors.acid,alignItems:'center',justifyContent:'center'},field:{minHeight:58,borderRadius:radii.medium,backgroundColor:colors.canvas,borderWidth:1,borderColor:colors.line,paddingHorizontal:17,flexDirection:'row',alignItems:'center',gap:10,marginTop:24},input:{flex:1,fontFamily:'Manrope_500Medium',fontSize:14,color:colors.ink},help:{fontFamily:'Manrope_400Regular',fontSize:11,lineHeight:17,color:colors.muted,marginTop:10},action:{alignItems:'flex-start',marginTop:22},notice:{fontFamily:'Manrope_600SemiBold',fontSize:11,color:colors.ink,backgroundColor:colors.acid,padding:10,borderRadius:12,marginTop:14},ready:{minHeight:70,flexDirection:'row',alignItems:'center',gap:12,borderTopWidth:1,borderTopColor:colors.line},readyIcon:{width:38,height:38,borderRadius:19,backgroundColor:colors.acid,alignItems:'center',justifyContent:'center'},readyTitle:{fontFamily:'Manrope_700Bold',fontSize:13,color:colors.ink},readyText:{fontFamily:'Manrope_400Regular',fontSize:10,color:colors.muted,marginTop:2}});
